name: tracking_app_mock
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.1.2
  equatable: ^2.0.5
  google_fonts: ^5.0.0
  provider: ^6.0.3
  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  web_socket_channel: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: Lettera
      fonts:
        - asset: assets/fonts/LetteraTextLLTT-Regular.ttf
    - family: LetteraMedium
      fonts:
        - asset: assets/fonts/LetteraTextLLTT-Medium.ttf
    - family: InstagridHeadline
      fonts:
        - asset: assets/fonts/InstagridHeadline-Regular.ttf
